In [2]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [11]:
data = pd.read_csv('df_buyed_orders.csv', sep=';') 
data.head(10)

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.03.2017 12:22,15.03.2017 0:00,3999117_TR,Доставлен,4819,3759.0,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55575453-56535648535679,107117_ku16@list.ru,Гость,IDL00028974351,ИнтернетДоставка,NaN
1,01.03.2017 12:31,17.03.2017 0:00,3999122_TR,Доставлен,3325,3325.0,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,...,0,1,1,01.03.2017 0:00,55574950-57515657535772,109117_mu17@mail.ru,Гость,IDL00038573351,ИнтернетДоставка,NaN
2,01.03.2017 11:38,14.03.2017 0:00,3999411_TR,Доставлен,528,528.0,Магазины,Безналичная,Ижевск,ИГРУШКИ,...,0,3,1,01.03.2017 0:00,55574854-56495552515179,guest_103117_gu28@workmail.ru,Гость,IDL00035791553,ИнтернетДоставка,NaN
3,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,3,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00025316250,ИнтернетДоставка,NaN
4,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,2,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00025320553,ИнтернетДоставка,NaN
5,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,1,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00024877755,ИнтернетДоставка,NaN
6,01.03.2017 10:39,03.03.2017 0:00,4000115_TR,Доставлен,13550,13550.0,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,4,1,01.03.2017 0:00,55574851-55504856515370,109117_mu18@yandex.ru,Мария,IDL00026577856,ИнтернетДоставка,NaN
7,01.03.2017 14:01,04.03.2017 0:00,4000127_TR,Доставлен,4754,4095.0,Магазины,Безналичная,Красково (Люберецкий район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,6,1,01.03.2017 0:00,55574948-52504948534879,56117_8u19@mail.ru,Ольга,IDL00036503553,ИнтернетДоставка,NaN
8,01.03.2017 14:01,04.03.2017 0:00,4000127_TR,Доставлен,4754,4095.0,Магазины,Безналичная,Красково (Люберецкий район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55574948-52504948534879,56117_8u19@mail.ru,Ольга,IDL00036502048,ИнтернетДоставка,NaN
9,01.03.2017 10:39,03.03.2017 0:00,4000257_TR,Доставлен,4543,4543.0,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55574853-53564848495777,115117_su23@mail.ru,Гость,IDL00031124048,ИнтернетДоставка,NaN

Используем номер заказа, как идентификатор

In [3]:
display(data[data['НомерЗаказаНаСайте'] == np.NaN])
display(data[data['НомерЗаказаНаСайте'] == 0])

Empty DataFrame
Columns: [Дата, ДатаДоставки, НомерЗаказаНаСайте, НовыйСтатус, СуммаЗаказаНаСайте, СуммаДокумента, МетодДоставки, ФормаОплаты, Регион, Группа2, Группа3, Группа4, Тип, Номенклатура, ТипТовара, Отменено, ПричинаОтмены, Количество, Цена, СуммаСтроки, ЦенаЗакупки, МесяцДатыЗаказа, ГодДатыЗаказа, ПВЗ_код, Статус, Гео, Маржа, СуммаУслуг, СуммаДоставки, НомерСтроки, КоличествоПроданоКлиенту, ДатаЗаказаНаСайте, Телефон_new, ЭлектроннаяПочта_new, Клиент, ID_SKU, ГородМагазина, МагазинЗаказа]
Index: []

[0 rows x 38 columns]

Empty DataFrame
Columns: [Дата, ДатаДоставки, НомерЗаказаНаСайте, НовыйСтатус, СуммаЗаказаНаСайте, СуммаДокумента, МетодДоставки, ФормаОплаты, Регион, Группа2, Группа3, Группа4, Тип, Номенклатура, ТипТовара, Отменено, ПричинаОтмены, Количество, Цена, СуммаСтроки, ЦенаЗакупки, МесяцДатыЗаказа, ГодДатыЗаказа, ПВЗ_код, Статус, Гео, Маржа, СуммаУслуг, СуммаДоставки, НомерСтроки, КоличествоПроданоКлиенту, ДатаЗаказаНаСайте, Телефон_new, ЭлектроннаяПочта_new, Клиент, ID_SKU, ГородМагазина, МагазинЗаказа]
Index: []

[0 rows x 38 columns]

Используем категории Группы2 в качестве переменных в MarketBasket

In [12]:
columns_mb = np.unique(data['Группа2'])
print('Количество уникальных значений в Группа2:', len(set(data['Группа2'])), '\nСами значения: ', set(data['Группа2']))

Количество уникальных значений в Группа2: 13
Сами значения:  {'ЖЕНСКИЕ ШТУЧКИ', 'КАНЦТОВАРЫ, КНИГИ, ДИСКИ', 'СОПУТСТВУЮЩИЕ ТОВАРЫ', 'ОБУВЬ', 'КРУПНОГАБАРИТНЫЙ ТОВАР', 'ДЕТСКОЕ ПИТАНИЕ', 'КОСМЕТИКА/ГИГИЕНА', 'ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА', 'ТОВАРЫ ДЛЯ КОРМЛЕНИЯ', 'ТОВАРЫ ДЛЯ ЖИВОТНЫХ', 'ИГРУШКИ', 'ТЕКСТИЛЬ, ТРИКОТАЖ', 'ПОДГУЗНИКИ'}

In [5]:
data['Группа2'].value_counts()

ИГРУШКИ                      52944
ТЕКСТИЛЬ, ТРИКОТАЖ           35851
ДЕТСКОЕ ПИТАНИЕ              27822
ПОДГУЗНИКИ                   25704
КОСМЕТИКА/ГИГИЕНА            19093
КРУПНОГАБАРИТНЫЙ ТОВАР       17629
ТОВАРЫ ДЛЯ КОРМЛЕНИЯ         14213
КАНЦТОВАРЫ, КНИГИ, ДИСКИ     11922
ОБУВЬ                         6174
ТОВАРЫ ДЛЯ ЖИВОТНЫХ           3619
СОПУТСТВУЮЩИЕ ТОВАРЫ           492
ЖЕНСКИЕ ШТУЧКИ                 391
ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА       22
Name: Группа2, dtype: int64

Посмотрим сколько уникальных клиентов vs уникальных заказов, соверешенными этими людьми

In [6]:
print('Уникальных клиентов:', len(set(data['Телефон_new'])))
print('Уникальных заказов:', len(set(data['НомерЗаказаНаСайте'])))

Уникальных клиентов: 58031
Уникальных заказов: 75598

# Market Basket по чекам

In [7]:
order_number = np.unique(data['НомерЗаказаНаСайте'])

market_basket = pd.DataFrame(columns=columns_mb)
market_basket.insert(0, 'Заказ', order_number)
market_basket.fillna(0, inplace=True)
market_basket.head(10)

,Заказ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,1303000313_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1303000319_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
2,1303000321_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
3,1303000323_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
4,1303000324_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
5,1303000325_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
6,1303000326_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
7,1303000327_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
8,1303000335_TR,0,0,0,0,0,0,0,0,0,0,0,0,0
9,1303000336_TR,0,0,0,0,0,0,0,0,0,0,0,0,0

Теперь заполняем эту таблицу. Смотрим какие категории товаров покупались в каждом заказе вместе

In [8]:
mb_loc = {key: i for i, key in enumerate(order_number)} 

for i in range(0, data.shape[0]): 
    j = mb_loc[data["НомерЗаказаНаСайте"][i]] 
    market_basket[data["Группа2"][i]][j] += data["КоличествоПроданоКлиенту"][i]

<ipython-input-8-61827227ef35>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  market_basket[data["Группа2"][i]][j] += data["КоличествоПроданоКлиенту"][i]

In [56]:
market_basket.sample(5)

,Заказ,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
64170,4442060_TR,0,0,1,0,0,0,0,0,0,0,0,0,0
25041,4187871_TR,0,0,0,0,1,0,0,2,0,0,0,0,0
61148,4426905_TR,63,0,0,0,17,0,0,2,0,0,0,0,0
62772,4435001_TR,0,0,0,0,0,0,0,1,0,0,0,0,0
62215,4431986_TR,49,0,0,0,0,0,0,1,0,0,0,0,4

In [10]:
market_basket.to_csv('MB_orders_buyed.csv', index=False, sep=';', encoding='utf-8-sig')

                       Пара категорий   support  confidence      lift
32       ИГРУШКИ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.061515    0.221427  0.494878
110      ТЕКСТИЛЬ, ТРИКОТАЖ & ИГРУШКИ  0.061515    0.137483  0.494878
62   КРУПНОГАБАРИТНЫЙ ТОВАР & ИГРУШКИ  0.040474    0.478733  1.723228
28   ИГРУШКИ & КРУПНОГАБАРИТНЫЙ ТОВАР  0.040474    0.145690  1.723228
80         ОБУВЬ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.036572    0.238761  0.533620
114        ТЕКСТИЛЬ, ТРИКОТАЖ & ОБУВЬ  0.036572    0.081737  0.533620
86               ПОДГУЗНИКИ & ИГРУШКИ  0.028768    0.131607  0.473726
30               ИГРУШКИ & ПОДГУЗНИКИ  0.028768    0.103553  0.473726

Считаем какие категории товаров покупаются чаще всего вместе

In [13]:
import itertools

info_mb = ['support', 'confidence', 'lift']
resulting_info_mb = pd.DataFrame(columns=info_mb)

perms = list(' & '.join(i) for i in itertools.permutations(columns_mb, 2))

In [12]:
perms[:10]

['ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ',
 'ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ',
 'ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ',
 'ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА',
 'ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР',
 'ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ',
 'ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ',
 'ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ',
 'ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ',
 'ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА']

In [13]:
len(perms)

156

In [14]:
resulting_info_mb.insert(0, 'Пара категорий', perms)
resulting_info_mb.fillna(0, inplace=True)
resulting_info_mb.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ        0           0     0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ        0           0     0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ        0           0     0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА        0           0     0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР        0           0     0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ        0           0     0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ        0           0     0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ        0           0     0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ        0           0     0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА        0           0     0

Сделали пустую таблицу, теперь заполняем

In [15]:
def support(perm, data):
    counter = 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(data.shape[0]):
        if data[fir][i] > 0 and data[sec][i] > 0:
            counter += 1
    return counter / len(data)

def confidence(perm, data):
    counter_both, counter_first = 0, 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(data.shape[0]):
        if data[fir][i] > 0: 
            counter_first += 1
            if data[sec][i] > 0:
                counter_both += 1
    return counter_both/counter_first

def denom(perm, data):
    counter_first = 0
    counter_second = 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(data.shape[0]):
        if data[fir][i] > 0:
            counter_first += 1
        if data[sec][i] > 0:
            counter_second += 1
    return (counter_first * counter_second) / data.shape[0]**2

In [16]:
print(perms[1])
x = perms[1].split(' & ')
x[1]

ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ

'ИГРУШКИ'

In [17]:
# resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'support'] = sup

In [18]:
for i in range(len(perms)):
    sup = support(perms[i], market_basket) 
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], market_basket) 
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'confidence'] = conf
    
    lift = sup / denom(perms[i], market_basket)
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb.head(10)

                                Пара категорий   support  confidence      lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ  0.000516    0.005611  2.232410
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ  0.016125    0.175370  0.546009
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ  0.005397    0.058697  1.001884
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА  0.022673    0.246583  2.411851
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР  0.004656    0.050640  0.247003
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ  0.002037    0.022155  0.372030
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ  0.035477    0.385844  1.566122
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ  0.000278    0.003021  0.566731
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.009815    0.106747  0.572860
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА  0.000053    0.000575  2.289652

Отсортируем, ведь support у A->B и B->A одинаковый

In [19]:
# df.sort_values(by=['col1', 'col2'])
resulting_info_mb.sort_values(by=['support', 'confidence'], ascending=False).head(10)

                         Пара категорий   support  confidence      lift
54       КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИ  0.050835    0.497218  2.018186
88       ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНА  0.050835    0.206336  2.018186
86                 ПОДГУЗНИКИ & ИГРУШКИ  0.035596    0.144483  0.449843
30                 ИГРУШКИ & ПОДГУЗНИКИ  0.035596    0.110827  0.449843
6          ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ  0.035477    0.385844  1.566122
84         ПОДГУЗНИКИ & ДЕТСКОЕ ПИТАНИЕ  0.035477    0.144000  1.566122
110        ТЕКСТИЛЬ, ТРИКОТАЖ & ИГРУШКИ  0.034154    0.183290  0.570665
32         ИГРУШКИ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.034154    0.106338  0.570665
38   КАНЦТОВАРЫ, КНИГИ, ДИСКИ & ИГРУШКИ  0.033440    0.570783  1.777113
26   ИГРУШКИ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ  0.033440    0.104114  1.777113

In [20]:
resulting_info_mb.to_csv('MarketBasket_orders.csv', index=False, sep=';', encoding='utf-8-sig')

# MarketBssket по клиентам

In [21]:
data = pd.read_csv('df_buyed_orders.csv', sep=';') 
data.head(10)

,Дата,ДатаДоставки,НомерЗаказаНаСайте,НовыйСтатус,СуммаЗаказаНаСайте,СуммаДокумента,МетодДоставки,ФормаОплаты,Регион,Группа2,...,СуммаДоставки,НомерСтроки,КоличествоПроданоКлиенту,ДатаЗаказаНаСайте,Телефон_new,ЭлектроннаяПочта_new,Клиент,ID_SKU,ГородМагазина,МагазинЗаказа
0,01.03.2017 12:22,15.03.2017 0:00,3999117_TR,Доставлен,4819,3759.0,Магазины,Безналичная,Челябинск,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55575453-56535648535679,107117_ku16@list.ru,Гость,IDL00028974351,ИнтернетДоставка,NaN
1,01.03.2017 12:31,17.03.2017 0:00,3999122_TR,Доставлен,3325,3325.0,Магазины,Безналичная,Нижневартовск,ИГРУШКИ,...,0,1,1,01.03.2017 0:00,55574950-57515657535772,109117_mu17@mail.ru,Гость,IDL00038573351,ИнтернетДоставка,NaN
2,01.03.2017 11:38,14.03.2017 0:00,3999411_TR,Доставлен,528,528.0,Магазины,Безналичная,Ижевск,ИГРУШКИ,...,0,3,1,01.03.2017 0:00,55574854-56495552515179,guest_103117_gu28@workmail.ru,Гость,IDL00035791553,ИнтернетДоставка,NaN
3,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,3,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00025316250,ИнтернетДоставка,NaN
4,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,2,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00025320553,ИнтернетДоставка,NaN
5,01.03.2017 9:02,03.03.2017 0:00,3999713_TR,Доставлен,1196,1196.0,Магазины,Безналичная,Подольск (Московская область район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,49,1,1,01.03.2017 0:00,55574948-52515357485779,111117_ou25@yandex.ru,Ольга,IDL00024877755,ИнтернетДоставка,NaN
6,01.03.2017 10:39,03.03.2017 0:00,4000115_TR,Доставлен,13550,13550.0,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,4,1,01.03.2017 0:00,55574851-55504856515370,109117_mu18@yandex.ru,Мария,IDL00026577856,ИнтернетДоставка,NaN
7,01.03.2017 14:01,04.03.2017 0:00,4000127_TR,Доставлен,4754,4095.0,Магазины,Безналичная,Красково (Люберецкий район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,6,1,01.03.2017 0:00,55574948-52504948534879,56117_8u19@mail.ru,Ольга,IDL00036503553,ИнтернетДоставка,NaN
8,01.03.2017 14:01,04.03.2017 0:00,4000127_TR,Доставлен,4754,4095.0,Магазины,Безналичная,Красково (Люберецкий район),"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55574948-52504948534879,56117_8u19@mail.ru,Ольга,IDL00036502048,ИнтернетДоставка,NaN
9,01.03.2017 10:39,03.03.2017 0:00,4000257_TR,Доставлен,4543,4543.0,Магазины,Безналичная,Москва,"ТЕКСТИЛЬ, ТРИКОТАЖ",...,0,3,1,01.03.2017 0:00,55574853-53564848495777,115117_su23@mail.ru,Гость,IDL00031124048,ИнтернетДоставка,NaN

In [22]:
order_number = np.unique(data["Телефон_new"])

order_number = np.delete(order_number, 0, 0)
market_basket = pd.DataFrame(columns=columns_mb)
market_basket.insert(0, 'Клиент', order_number)
market_basket.fillna(0, inplace=True)
market_basket.head(10)

,Клиент,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,32555749-545749525150 .,0,0,0,0,0,0,0,0,0,0,0,0,0
1,55494851-56495152535476,0,0,0,0,0,0,0,0,0,0,0,0,0
2,55574848-48485149515175,0,0,0,0,0,0,0,0,0,0,0,0,0
3,55574848-48485149515377,0,0,0,0,0,0,0,0,0,0,0,0,0
4,55574848-48494948544878,0,0,0,0,0,0,0,0,0,0,0,0,0
5,55574848-48495057545270,0,0,0,0,0,0,0,0,0,0,0,0,0
6,55574848-48504851505372,0,0,0,0,0,0,0,0,0,0,0,0,0
7,55574848-48504852495679,0,0,0,0,0,0,0,0,0,0,0,0,0
8,55574848-48504951495271,0,0,0,0,0,0,0,0,0,0,0,0,0
9,55574848-48504956565678,0,0,0,0,0,0,0,0,0,0,0,0,0

Удаляем клиента с телефоном 0

In [27]:
data = data.loc[data["Телефон_new"] != '0']
market_basket = market_basket.loc[market_basket['Клиент'] != '0']
market_basket.head(10)

,Клиент,ДЕТСКОЕ ПИТАНИЕ,ЖЕНСКИЕ ШТУЧКИ,ИГРУШКИ,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ",КОСМЕТИКА/ГИГИЕНА,КРУПНОГАБАРИТНЫЙ ТОВАР,ОБУВЬ,ПОДГУЗНИКИ,СОПУТСТВУЮЩИЕ ТОВАРЫ,"ТЕКСТИЛЬ, ТРИКОТАЖ",ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ
0,32555749-545749525150 .,0,0,0,0,0,0,0,0,0,0,0,0,0
1,55494851-56495152535476,0,0,0,0,0,0,0,0,0,0,0,0,0
2,55574848-48485149515175,0,0,0,0,0,0,0,0,0,0,0,0,0
3,55574848-48485149515377,0,0,0,0,0,0,0,0,0,0,0,0,0
4,55574848-48494948544878,0,0,0,0,0,0,0,0,0,0,0,0,0
5,55574848-48495057545270,0,0,0,0,0,0,0,0,0,1,0,0,0
6,55574848-48504851505372,0,0,0,0,0,0,0,0,0,0,0,0,0
7,55574848-48504852495679,0,0,0,0,0,0,0,0,0,0,0,0,0
8,55574848-48504951495271,0,0,0,0,0,0,0,0,0,0,0,0,0
9,55574848-48504956565678,0,0,0,0,0,0,0,0,0,0,0,0,0

In [28]:
order_number

array(['32555749-545749525150 .', '55494851-56495152535476',
       '55574848-48485149515175', ..., '56575655-52525750505484',
       '57484948-48505057565793', '57495452-49485054525597'], dtype=object)

In [41]:
market_basket = market_basket.reset_index(drop=True)
data = data.reset_index(drop=True)

In [42]:
data['Телефон_new'][139]
# data.loc[0, "Телефон_new"]

'55575555-52505749574975'

In [43]:
mb_loc = {key: i for i, key in enumerate(order_number)} 

for i in range(len(data)): 
    temp = data["Телефон_new"][i]
    j = mb_loc[temp] 
    market_basket.loc[j, data.loc[i, "Группа2"]] += data["КоличествоПроданоКлиенту"][i]

In [44]:
info_mb = ['support', 'confidence', 'lift']
resulting_info_mb = pd.DataFrame(columns=info_mb)

perms = list(' & '.join(i) for i in itertools.permutations(columns_mb, 2))

In [45]:
resulting_info_mb.insert(0, 'Пара категорий', perms)
resulting_info_mb.fillna(0, inplace=True)
resulting_info_mb.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ        0           0     0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ        0           0     0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ        0           0     0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА        0           0     0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР        0           0     0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ        0           0     0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ        0           0     0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ        0           0     0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ        0           0     0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА        0           0     0

In [46]:
for i in range(len(perms)):
    sup = support(perms[i], market_basket) 
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], market_basket) 
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'confidence'] = conf
    
    lift = sup / denom(perms[i], market_basket)
    resulting_info_mb.loc[resulting_info_mb['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb.head(10)

                                Пара категорий   support  confidence      lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ  0.000775    0.008636  2.863558
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ  0.025556    0.284590  0.779771
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ  0.008840    0.098446  1.429271
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА  0.029037    0.323354  2.855617
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР  0.009409    0.104778  0.428491
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ  0.004274    0.047592  0.690781
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ  0.044029    0.490309  1.987193
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ  0.000534    0.005949  0.892036
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.016664    0.185569  0.943866
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА  0.000069    0.000768  2.344433

In [57]:
x = resulting_info_mb.sort_values(by=['support', 'confidence'], ascending=False).head(10)

In [58]:
x * 100

,Пара категорий,support,confidence,lift
54,КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИКОСМЕТИКА/ГИГИЕН...,6.284680,55.501446,224.944049
88,ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНАПОДГУЗНИКИ & КОС...,6.284680,25.471435,224.944049
86,ПОДГУЗНИКИ & ИГРУШКИПОДГУЗНИКИ & ИГРУШКИПОДГУЗ...,5.628123,22.810448,62.500133
30,ИГРУШКИ & ПОДГУЗНИКИИГРУШКИ & ПОДГУЗНИКИИГРУШК...,5.628123,15.420936,62.500133
110,"ТЕКСТИЛЬ, ТРИКОТАЖ & ИГРУШКИТЕКСТИЛЬ, ТРИКОТАЖ...",5.505773,28.004207,76.730920
32,"ИГРУШКИ & ТЕКСТИЛЬ, ТРИКОТАЖИГРУШКИ & ТЕКСТИЛЬ...",5.505773,15.085698,76.730920
151,ТОВАРЫ ДЛЯ КОРМЛЕНИЯ & ПОДГУЗНИКИТОВАРЫ ДЛЯ КО...,4.728589,39.681851,160.828175
95,ПОДГУЗНИКИ & ТОВАРЫ ДЛЯ КОРМЛЕНИЯПОДГУЗНИКИ & ...,4.728589,19.164688,160.828175
38,"КАНЦТОВАРЫ, КНИГИ, ДИСКИ & ИГРУШКИКАНЦТОВАРЫ, ...",4.427021,64.273205,176.107185
26,"ИГРУШКИ & КАНЦТОВАРЫ, КНИГИ, ДИСКИИГРУШКИ & КА...",4.427021,12.129940,176.107185

In [48]:
resulting_info_mb.to_csv('MarketBasket_сlients.csv', index=False, sep=';', encoding='utf-8-sig')

## MarketBasket по кластерам
номер кластера смотрим в labels = 0,1,2,3

In [5]:
import itertools

In [14]:
data = pd.read_csv('vitrina_with_clusters_4.csv', sep=';') 
data.head(10)

,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,Ценность клиента_buyed,Абсолютная маржа_all,...,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,Безналичная,Наличная,ИнтернетДоставка,Калуга,Москва,Ростов-на-Дону,Саратов,Другой,Labels
0,2271,0.604150,2271.000000,4819,1,7,7,1,2271,2729,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
1,2176,0.654436,2176.000000,3325,1,1,1,1,2176,2176,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
2,204,0.386364,204.000000,528,1,4,4,1,204,204,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,759,0.345628,379.500000,1147,2,6,3,1,759,1784,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2
4,1510,0.242026,755.000000,3449,2,9,4,1,1510,1649,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2
5,3121,0.309010,1040.333333,3367,3,10,3,1,3121,3121,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1
6,1029,0.358537,1029.000000,2870,1,3,3,1,1029,1029,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3
7,1771,0.524120,885.500000,1739,2,2,1,1,1771,1771,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3
8,355,0.493056,355.000000,819,1,1,1,1,355,355,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3
9,1025,0.669935,1025.000000,1530,1,1,1,1,1025,1025,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3

In [15]:
data[data['ИнтернетДоставка'] < 1]

,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,Ценность клиента_buyed,Абсолютная маржа_all,...,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,Безналичная,Наличная,ИнтернетДоставка,Калуга,Москва,Ростов-на-Дону,Саратов,Другой,Labels
1843,4273,0.429102,1424.333333,3352,3,6,2,1,4273,4273,...,0.0,1.0,0.0,0.833333,0.166667,0.000000,0.0,0.0,0.0,1
1999,3485,0.419981,1742.500000,4149,2,2,1,1,3485,3485,...,0.0,1.0,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,1
3882,80,0.275862,80.000000,290,1,1,1,1,80,80,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
3999,76,0.292308,76.000000,260,1,1,1,1,76,76,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
5896,356,0.199888,178.000000,915,2,4,2,1,356,356,...,0.0,1.0,0.0,0.750000,0.000000,0.250000,0.0,0.0,0.0,0
5991,2927,0.581100,1463.500000,2543,2,3,2,1,2927,2927,...,0.0,1.0,0.0,0.666667,0.000000,0.333333,0.0,0.0,0.0,1
9753,449,0.160644,224.500000,1447,2,5,2,1,449,449,...,0.0,1.0,0.0,0.800000,0.200000,0.000000,0.0,0.0,0.0,0
10338,1941,0.138851,970.500000,7059,2,23,12,1,1941,1941,...,0.0,1.0,0.0,0.956522,0.000000,0.043478,0.0,0.0,0.0,2
15312,1209,0.252190,604.500000,2397,2,5,2,1,1209,1209,...,0.0,1.0,0.0,0.800000,0.200000,0.000000,0.0,0.0,0.0,3
17217,138,0.300000,138.000000,460,1,1,1,1,138,138,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
20904,42,0.240000,42.000000,175,1,1,1,1,42,42,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
25244,462,0.178654,231.000000,2944,2,3,2,1,462,462,...,0.0,1.0,0.0,0.666667,0.000000,0.333333,0.0,0.0,0.0,0
26635,79,0.273356,79.000000,289,1,1,1,1,79,79,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
28499,627,0.697442,627.000000,899,1,1,1,1,627,627,...,0.0,1.0,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,3
29878,1498,0.247685,749.000000,3024,2,5,2,1,1498,1498,...,0.0,1.0,0.0,0.800000,0.000000,0.200000,0.0,0.0,0.0,3
29933,788,0.181274,262.666667,1482,3,4,1,1,788,788,...,0.0,1.0,0.0,0.750000,0.000000,0.250000,0.0,0.0,0.0,3
31613,127,0.334211,127.000000,380,1,1,1,1,127,127,...,0.0,1.0,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,0
32387,261,0.342071,261.000000,763,1,1,1,1,261,261,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
35536,240,0.342857,240.000000,700,1,1,1,1,240,240,...,0.0,1.0,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,0
35697,820,0.253478,820.000000,3235,1,1,1,1,820,820,...,0.0,1.0,0.0,0.000000,1.000000,0.000000,0.0,0.0,0.0,3
37785,2290,0.318498,1145.000000,3595,2,2,1,1,2290,2290,...,0.0,1.0,0.0,0.500000,0.500000,0.000000,0.0,0.0,0.0,1
38008,51,0.380597,51.000000,134,1,1,1,1,51,51,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
40523,125,0.411184,125.000000,304,1,1,1,1,125,125,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
41343,446,0.249720,446.000000,1786,1,1,1,1,446,446,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
42856,540,0.287234,540.000000,1880,1,1,1,1,540,540,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0
43579,216,0.193029,216.000000,1119,1,1,1,1,216,216,...,0.0,1.0,0.0,0.000000,0.000000,1.000000,0.0,0.0,0.0,0

In [16]:
df_1 = data[data['Labels'] == 0]
df_2 = data[data['Labels'] == 1]
df_3 = data[data['Labels'] == 2]
df_4 = data[data['Labels'] == 3]

df_1 = df_1.reset_index(drop=True)
df_2 = df_2.reset_index(drop=True)
df_3 = df_3.reset_index(drop=True)
df_4 = df_4.reset_index(drop=True)

display(df_1[df_1['Кол-во уникальных клиентов_buyed'] == 1])
df_1.columns

,Абсолютная маржа_buyed,Маржа_buyed,Средняя маржа_buyed,Средний чек_buyed,Кол-во чеков_buyed,Кол-во товаров_buyed,Среднее кол-во товаров в чеке_buyed,Кол-во уникальных клиентов_buyed,Ценность клиента_buyed,Абсолютная маржа_all,...,ТОВАРЫ ДЛЯ ЖИВОТНЫХ,Безналичная,Наличная,ИнтернетДоставка,Калуга,Москва,Ростов-на-Дону,Саратов,Другой,Labels
0,204,0.386364,204.0,528,1,4,4,1,204,204,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
1,147,0.047557,147.0,3091,1,2,2,1,147,147,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
2,115,0.164286,115.0,700,1,1,1,1,115,115,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,436,0.165843,436.0,2629,1,6,6,1,436,436,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
4,497,0.220791,497.0,2300,1,7,7,1,497,497,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22056,357,0.300000,357.0,1289,1,1,1,1,357,357,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
22057,144,0.169611,144.0,849,1,1,1,1,144,144,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
22058,148,0.334086,148.0,542,1,1,1,1,148,148,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
22059,38,0.101333,38.0,474,1,1,1,1,38,38,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0
22060,57,0.178125,57.0,369,1,1,1,1,57,57,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0

Index(['Абсолютная маржа_buyed', 'Маржа_buyed', 'Средняя маржа_buyed',
       'Средний чек_buyed', 'Кол-во чеков_buyed', 'Кол-во товаров_buyed',
       'Среднее кол-во товаров в  чеке_buyed',
       'Кол-во уникальных клиентов_buyed', 'Ценность клиента_buyed',
       'Абсолютная маржа_all', 'Маржа_all', 'Средняя маржа_all',
       'Кол-во чеков_all', 'Кол-во товаров_all',
       'Кол-во уникальных клиентов_all', 'Ценность клиента_all',
       'КРУПНОГАБАРИТНЫЙ ТОВАР', 'ТЕКСТИЛЬ, ТРИКОТАЖ', 'ОБУВЬ',
       'КАНЦТОВАРЫ, КНИГИ, ДИСКИ', 'ТОВАРЫ ДЛЯ КОРМЛЕНИЯ', 'ИГРУШКИ',
       'КОСМЕТИКА/ГИГИЕНА', 'СОПУТСТВУЮЩИЕ ТОВАРЫ', 'ЖЕНСКИЕ ШТУЧКИ',
       'ПОДГУЗНИКИ', 'ДЕТСКОЕ ПИТАНИЕ', 'ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА',
       'ТОВАРЫ ДЛЯ ЖИВОТНЫХ', 'Безналичная', 'Наличная', 'ИнтернетДоставка',
       'Калуга', 'Москва', 'Ростов-на-Дону', 'Саратов', 'Другой', 'Labels'],
      dtype='object')

Кластер 1

In [17]:
info_mb = ['support', 'confidence', 'lift']
resulting_info_mb_1 = pd.DataFrame(columns=info_mb)

resulting_info_mb_1.insert(0, 'Пара категорий', perms)
resulting_info_mb_1.fillna(0, inplace=True)

perms = list(' & '.join(i) for i in itertools.permutations(columns_mb, 2))

In [18]:
def support(perm, data):
    counter = 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(len(data)):
        if data.loc[i, fir] > 0 and data.loc[i, sec] > 0:
            counter += 1
    return counter / len(data)

def confidence(perm, data):
    counter_both, counter_first = 0, 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(data.shape[0]):
        if data[fir][i] > 0: 
            counter_first += 1
            if data[sec][i] > 0:
                counter_both += 1
    if counter_first == 0:
        return 0
    return counter_both/counter_first

def denom(perm, data):
    counter_first = 0
    counter_second = 0
    fir =  perm.split(' & ')[0]
    sec = perm.split(' & ')[1]
    for i in range(data.shape[0]):
        if data[fir][i] > 0:
            counter_first += 1
        if data[sec][i] > 0:
            counter_second += 1
    return (counter_first * counter_second) / data.shape[0]**2

In [19]:
for i in range(len(perms)):
    sup = support(perms[i], df_1) 
    resulting_info_mb_1.loc[resulting_info_mb_1['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], df_1) 
    resulting_info_mb_1.loc[resulting_info_mb_1['Пара категорий'] == perms[i], 'confidence'] = conf
    
    if denom(perms[i], df_1) != 0:
        lift = sup / denom(perms[i], df_1)
    else:
        lift = 0
    resulting_info_mb_1.loc[resulting_info_mb_1['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb_1.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ      0.0         0.0   0.0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ      0.0         0.0   0.0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ      0.0         0.0   0.0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА      0.0         0.0   0.0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР      0.0         0.0   0.0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ      0.0         0.0   0.0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ      0.0         0.0   0.0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ      0.0         0.0   0.0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ      0.0         0.0   0.0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА      0.0         0.0   0.0

In [20]:
resulting_info_mb_1.sort_values(by=['support', 'confidence'], ascending=False).head(10)

                         Пара категорий   support  confidence      lift
86                 ПОДГУЗНИКИ & ИГРУШКИ  0.044468    0.161349  0.281384
30                 ИГРУШКИ & ПОДГУЗНИКИ  0.044468    0.077549  0.281384
54       КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИ  0.044196    0.449931  1.632553
88       ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНА  0.044196    0.160362  1.632553
38   КАНЦТОВАРЫ, КНИГИ, ДИСКИ & ИГРУШКИ  0.038167    0.506924  0.884051
26   ИГРУШКИ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ  0.038167    0.066561  0.884051
151   ТОВАРЫ ДЛЯ КОРМЛЕНИЯ & ПОДГУЗНИКИ  0.032682    0.250783  0.909953
95    ПОДГУЗНИКИ & ТОВАРЫ ДЛЯ КОРМЛЕНИЯ  0.032682    0.118586  0.909953
146      ТОВАРЫ ДЛЯ КОРМЛЕНИЯ & ИГРУШКИ  0.025112    0.192696  0.336052
35       ИГРУШКИ & ТОВАРЫ ДЛЯ КОРМЛЕНИЯ  0.025112    0.043794  0.336052

In [21]:
resulting_info_mb_1.to_csv('MarketBasket_cluster_1.csv', index=False, sep=';', encoding='utf-8-sig')

Кластер 2

In [22]:
resulting_info_mb_2 = pd.DataFrame(columns=info_mb)
resulting_info_mb_2.insert(0, 'Пара категорий', perms)
resulting_info_mb_2.fillna(0, inplace=True)

In [23]:
for i in range(len(perms)):
    sup = support(perms[i], df_2) 
    resulting_info_mb_2.loc[resulting_info_mb_2['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], df_2) 
    resulting_info_mb_2.loc[resulting_info_mb_2['Пара категорий'] == perms[i], 'confidence'] = conf
    
    if denom(perms[i], df_2) != 0:
        lift = sup / denom(perms[i], df_2)
    else:
        lift = 0
    resulting_info_mb_2.loc[resulting_info_mb_2['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb_2.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ      0.0         0.0   0.0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ      0.0         0.0   0.0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ      0.0         0.0   0.0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА      0.0         0.0   0.0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР      0.0         0.0   0.0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ      0.0         0.0   0.0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ      0.0         0.0   0.0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ      0.0         0.0   0.0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ      0.0         0.0   0.0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА      0.0         0.0   0.0

In [24]:
resulting_info_mb_2.sort_values(by=['support', 'confidence'], ascending=False).head(10)

,Пара категорий,support,confidence,lift
54,КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИ,0.115694,0.703583,1.352125
88,ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНА,0.115694,0.222337,1.352125
62,КРУПНОГАБАРИТНЫЙ ТОВАР & ИГРУШКИ,0.106856,0.465035,1.538034
28,ИГРУШКИ & КРУПНОГАБАРИТНЫЙ ТОВАР,0.106856,0.353410,1.538034
30,ИГРУШКИ & ПОДГУЗНИКИ,0.096411,0.318866,0.612788
86,ПОДГУЗНИКИ & ИГРУШКИ,0.096411,0.185280,0.612788
68,"КРУПНОГАБАРИТНЫЙ ТОВАР & ТЕКСТИЛЬ, ТРИКОТАЖ",0.089984,0.391608,1.155028
113,"ТЕКСТИЛЬ, ТРИКОТАЖ & КРУПНОГАБАРИТНЫЙ ТОВАР",0.089984,0.265403,1.155028
115,"ТЕКСТИЛЬ, ТРИКОТАЖ & ПОДГУЗНИКИ",0.079004,0.233017,0.447806
92,"ПОДГУЗНИКИ & ТЕКСТИЛЬ, ТРИКОТАЖ",0.079004,0.151827,0.447806

In [25]:
resulting_info_mb_2.to_csv('MarketBasket_cluster_2.csv', index=False, sep=';', encoding='utf-8-sig')

Кластер 3

In [26]:
resulting_info_mb_3 = pd.DataFrame(columns=info_mb)
resulting_info_mb_3.insert(0, 'Пара категорий', perms)
resulting_info_mb_3.fillna(0, inplace=True)

In [27]:
for i in range(len(perms)):
    sup = support(perms[i], df_3) 
    resulting_info_mb_3.loc[resulting_info_mb_3['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], df_3) 
    resulting_info_mb_3.loc[resulting_info_mb_3['Пара категорий'] == perms[i], 'confidence'] = conf
    
    if denom(perms[i], df_3) != 0:
        lift = sup / denom(perms[i], df_3)
    else:
        lift = 0
    resulting_info_mb_3.loc[resulting_info_mb_3['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb_3.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ      0.0         0.0   0.0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ      0.0         0.0   0.0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ      0.0         0.0   0.0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА      0.0         0.0   0.0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР      0.0         0.0   0.0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ      0.0         0.0   0.0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ      0.0         0.0   0.0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ      0.0         0.0   0.0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ      0.0         0.0   0.0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА      0.0         0.0   0.0

In [28]:
resulting_info_mb_3.sort_values(by=['support', 'confidence'], ascending=False).head(10)

                               Пара категорий   support  confidence      lift
54             КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИ  0.280922    0.667155  1.374770
88             ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНА  0.280922    0.578880  1.374770
110              ТЕКСТИЛЬ, ТРИКОТАЖ & ИГРУШКИ  0.254785    0.591778  1.007869
32               ИГРУШКИ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.254785    0.433929  1.007869
86                       ПОДГУЗНИКИ & ИГРУШКИ  0.226178    0.466073  0.793778
30                       ИГРУШКИ & ПОДГУЗНИКИ  0.226178    0.385209  0.793778
148  ТОВАРЫ ДЛЯ КОРМЛЕНИЯ & КОСМЕТИКА/ГИГИЕНА  0.213007    0.616806  1.464838
59   КОСМЕТИКА/ГИГИЕНА & ТОВАРЫ ДЛЯ КОРМЛЕНИЯ  0.213007    0.505865  1.464838
151         ТОВАРЫ ДЛЯ КОРМЛЕНИЯ & ПОДГУЗНИКИ  0.211566    0.612634  1.262421
95          ПОДГУЗНИКИ & ТОВАРЫ ДЛЯ КОРМЛЕНИЯ  0.211566    0.435963  1.262421

In [29]:
resulting_info_mb_3.to_csv('MarketBasket_cluster_3.csv', index=False, sep=';', encoding='utf-8-sig')

Кластер 4

In [30]:
resulting_info_mb_4 = pd.DataFrame(columns=info_mb)
resulting_info_mb_4.insert(0, 'Пара категорий', perms)
resulting_info_mb_4.fillna(0, inplace=True)

In [31]:
for i in range(len(perms)):
    sup = support(perms[i], df_4) 
    resulting_info_mb_4.loc[resulting_info_mb_4['Пара категорий'] == perms[i], 'support'] = sup
    
    conf = confidence(perms[i], df_4) 
    resulting_info_mb_4.loc[resulting_info_mb_4['Пара категорий'] == perms[i], 'confidence'] = conf
    
    if denom(perms[i], df_4) != 0:
        lift = sup / denom(perms[i], df_4)
    else:
        lift = 0
    resulting_info_mb_4.loc[resulting_info_mb_4['Пара категорий'] == perms[i], 'lift'] = lift
resulting_info_mb_4.head(10)

                                Пара категорий  support  confidence  lift
0             ДЕТСКОЕ ПИТАНИЕ & ЖЕНСКИЕ ШТУЧКИ      0.0         0.0   0.0
1                    ДЕТСКОЕ ПИТАНИЕ & ИГРУШКИ      0.0         0.0   0.0
2   ДЕТСКОЕ ПИТАНИЕ & КАНЦТОВАРЫ, КНИГИ, ДИСКИ      0.0         0.0   0.0
3          ДЕТСКОЕ ПИТАНИЕ & КОСМЕТИКА/ГИГИЕНА      0.0         0.0   0.0
4     ДЕТСКОЕ ПИТАНИЕ & КРУПНОГАБАРИТНЫЙ ТОВАР      0.0         0.0   0.0
5                      ДЕТСКОЕ ПИТАНИЕ & ОБУВЬ      0.0         0.0   0.0
6                 ДЕТСКОЕ ПИТАНИЕ & ПОДГУЗНИКИ      0.0         0.0   0.0
7       ДЕТСКОЕ ПИТАНИЕ & СОПУТСТВУЮЩИЕ ТОВАРЫ      0.0         0.0   0.0
8         ДЕТСКОЕ ПИТАНИЕ & ТЕКСТИЛЬ, ТРИКОТАЖ      0.0         0.0   0.0
9  ДЕТСКОЕ ПИТАНИЕ & ТЕХНИКА И ТОВАРЫ ДЛЯ ДОМА      0.0         0.0   0.0

In [32]:
resulting_info_mb_4.sort_values(by=['support', 'confidence'], ascending=False).head(10)

                       Пара категорий   support  confidence      lift
32       ИГРУШКИ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.061515    0.221427  0.494878
110      ТЕКСТИЛЬ, ТРИКОТАЖ & ИГРУШКИ  0.061515    0.137483  0.494878
62   КРУПНОГАБАРИТНЫЙ ТОВАР & ИГРУШКИ  0.040474    0.478733  1.723228
28   ИГРУШКИ & КРУПНОГАБАРИТНЫЙ ТОВАР  0.040474    0.145690  1.723228
80         ОБУВЬ & ТЕКСТИЛЬ, ТРИКОТАЖ  0.036572    0.238761  0.533620
114        ТЕКСТИЛЬ, ТРИКОТАЖ & ОБУВЬ  0.036572    0.081737  0.533620
86               ПОДГУЗНИКИ & ИГРУШКИ  0.028768    0.131607  0.473726
30               ИГРУШКИ & ПОДГУЗНИКИ  0.028768    0.103553  0.473726
54     КОСМЕТИКА/ГИГИЕНА & ПОДГУЗНИКИ  0.028462    0.365064  1.670068
88     ПОДГУЗНИКИ & КОСМЕТИКА/ГИГИЕНА  0.028462    0.130207  1.670068

In [33]:
resulting_info_mb_4.to_csv('MarketBasket_cluster_4.csv', index=False, sep=';', encoding='utf-8-sig')